# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerTreeToImage
                                 A QGIS plugin
 This plugin exports each layer in the table of contents (tree) to an image.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-17
        copyright            : (C) 2020 by GETC
        email                : ahmad@getc.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerTreeToImage class from file LayerTreeToImage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Layer_Tree_To_Image import LayerTreeToImage
    return LayerTreeToImage(iface)
