# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerTreeToImageDialog
                                 A QGIS plugin
 This plugin exports each layer in the table of contents (tree) to an image.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-17
        git sha              : $Format:%H$
        copyright            : (C) 2020 by GETC
        email                : ahmad@getc.co.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os, sys

from PyQt5.QtGui import QFont, QIcon
from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QPersistentModelIndex, Qt, QItemSelectionModel
from PyQt5 import uic

from qgis.PyQt.QtWidgets import QAbstractItemView
from qgis.core import *
from qgis.utils import iface

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Layer_Tree_To_Image_dialog_base.ui'))


class LayerTreeToImageDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(LayerTreeToImageDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        # Keep the Layer Tree To Image Dialog at the top of QGIS window
        self.setWindowFlags(QtCore.Qt.Window)
        # set the title 
        self.setWindowTitle("Layer Tree To Image")      
        
        self.loadBtn.clicked.connect(self.load_layer)
        self.loadBtn.setFixedWidth(150)
        self.refreshBtn.clicked.connect(self.selectLayer)
        self.refreshBtn.setFixedWidth(150)
        
        self.OutFolderBtn.clicked.connect(self.out_path)
        self.OutFolderTxtEdit.textChanged.connect(self.ok_enabled)
        self.allLyrRadBtn.clicked.connect(self.all_check)
        self.allLyrRadBtn_2.clicked.connect(self.all_check)
        self.selLyrRadBtn.clicked.connect(self.select_check)
        self.selLyrRadBtn_2.clicked.connect(self.select_check)
        self.buttonBox.button(QDialogButtonBox.Ok).setEnabled(False)
        
        self.removeBtn.setText(" Delete Row")
        self.removeBtn.clicked.connect(self.deleteRow)
        removeBtn_icon = QIcon()
        removeBtn_icon.addPixmap(QtGui.QPixmap(os.path.join(os.path.dirname(os.path.abspath(__file__)), "Remove_Icon.png")))
        self.removeBtn.setIcon(removeBtn_icon)
        self.removeBtn.setIconSize(QtCore.QSize(20,20))
        
        self.layerTable.setMinimumHeight(250)
        self.layerTable.setMinimumWidth(250)
        self.layerTable.setColumnCount(1)
        self.layerTable.setHorizontalHeaderLabels(['Layer Name'])
        self.layerTable.horizontalHeader().setStyleSheet("""
            QHeaderView::section {
                color: Black;
                background-color: rgb(255, 212, 212);
                border: 0.08em solid rgb(220, 220, 220);
            }
            """)

        font = QFont()
        font.setBold(True)
        self.layerTable.horizontalHeader().setFont(font)
        header = self.layerTable.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        self.layerTable.setSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        self.layerTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        # Set selection to be by row instead of individual cell
        self.layerTable.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)
        # Enter cell edit mode by single-click
        self.layerTable.setEditTriggers(QAbstractItemView.CurrentChanged)

        self.group = QButtonGroup()
        self.group.addButton(self.allLyrRadBtn)        
        self.group.addButton(self.allLyrRadBtn_2)        
        self.group.addButton(self.selLyrRadBtn)        
        self.group.addButton(self.selLyrRadBtn_2)        
        
        self.lineEdit.setStyleSheet("""
            QLineEdit {
                color: rgb(0,0,0);
                background-color: transparent;
                border: transparent;
            }
            """)
        self.lineEdit_2.setStyleSheet("""
            QLineEdit {
                color: rgb(0,0,0);
                background-color: transparent;
                border: transparent;
            }
            """)
        self.lineEdit.setText('second(s)')
        # Disable text editing 
        self.lineEdit.setEnabled(False)
        
        # Adjust the maximum value of spinBox
        self.doubleSpinBox.setMaximum(300000)
        # Set the default value to 1 second
        self.doubleSpinBox.setValue(1)

        # Adjust the maximum value of spinBox
        self.doubleSpinBox_2.setMaximum(300000)
        # Set the default value to 1 second
        self.doubleSpinBox_2.setValue(1)

    def out_path(self):
        """ select target directory """
        getOutputDir = QtWidgets.QFileDialog.getExistingDirectory(self, \
            "Select Directory")
        # TODO cancel
        self.OutFolderTxtEdit.setText(getOutputDir)
        
    def deleteRow(self): # called when delete button is triggerd on selected row/s
        if self.layerTable.selectionModel().hasSelection():
            indexes =[QPersistentModelIndex(index) for index in self.layerTable.selectionModel().selectedRows()]
            for index in indexes:
                print('Deleting row %d...' % index.row())
                self.layerTable.removeRow(index.row())
                
    def ok_enabled(self):
        if not self.OutFolderTxtEdit.text() == '':
            self.buttonBox.button(QDialogButtonBox.Ok).setEnabled(True)
        else:
            self.buttonBox.button(QDialogButtonBox.Ok).setEnabled(False)
    
    def all_check(self):
        layerTable = self.layerTable
        while True:
            if (self.allLyrRadBtn.isChecked() or self.allLyrRadBtn_2.isChecked()):
                if layerTable.rowCount() == 0:
                    iface.messageBar().pushMessage("Warning", 'No layers loaded, \
                                    please load layers, then select.', level=Qgis.Warning) 
                break          

        if self.allLyrRadBtn.isChecked():
            if layerTable.rowCount() > 0:
                iface.actionHideAllLayers().trigger()

        if self.allLyrRadBtn_2.isChecked():
            if layerTable.rowCount() > 0:
                iface.actionShowAllLayers().trigger()
                
    def select_check(self):
        layerTable = self.layerTable
        while True:
            if (self.selLyrRadBtn.isChecked() or self.selLyrRadBtn_2.isChecked()):
                if layerTable.rowCount() == 0:
                    iface.messageBar().pushMessage("Warning", 'No layers loaded, \
                                    please load layers, then select.', level=Qgis.Warning)

                break

        if self.selLyrRadBtn.isChecked():
            if layerTable.rowCount() > 0:
                iface.actionHideSelectedLayers().trigger()

        if self.selLyrRadBtn_2.isChecked():
            if layerTable.rowCount() > 0:
                iface.actionShowSelectedLayers().trigger()
            
    def load_layer(self):
        iface.layerTreeView().clearSelection()
        total_layer_counter = 0
        lyrs = [lyr.name() for lyr in QgsProject.instance().mapLayers().values()]
        if len(lyrs) == 0:
            iface.messageBar().pushMessage("Error", "There is no layers loaded \
                            in your project.", level=Qgis.Critical)
        for lyr in lyrs:
            total_layer_counter+=1
        
        row_nb = total_layer_counter
        col_nb = 1
        self.layerTable.setRowCount(row_nb)
        self.layerTable.setColumnCount(col_nb)
        curr_row = 0
        
        lyrs = [lyr.name() for lyr in QgsProject.instance().mapLayers().values()]
        for lyr in lyrs:
            # Add following line to only populate first column
            # of folder and sub-folder names
            col = 0
            lyr_item = QTableWidgetItem(lyr)
            # Make the folder column read-only
            lyr_item.setFlags(lyr_item.flags() ^ Qt.ItemIsEditable)
            lyr_item.setBackground(QtGui.QColor(236, 252, 229))
            self.layerTable.setItem(curr_row,col,lyr_item)
            curr_row += 1

    def selectLayer(self, layerTable, column=0):
        layerTable = self.layerTable
        if layerTable.rowCount() == 0:
            iface.messageBar().pushMessage("Error", 'No layers loaded, please load layers.', \
                            level=Qgis.Critical)
        # rowCount() This property holds the number of rows in the table
        for row in range(layerTable.rowCount()):         
            # item(row, 0) Returns the item for the given row and column if one 
            # has been set; otherwise returns nullptr.
            _item = self.layerTable.item(row, column) 
            if _item:            
                item = self.layerTable.item(row, column).text()
                print(f'row: {row}, column: {column}, item={item}')
            # enable multiSelection in the layer tree in QGIS 
            iface.layerTreeView().setSelectionMode( QAbstractItemView.MultiSelection ) 
            # loop over the laters in the layer tree to activate and select
            lyrs = [lyr for lyr in QgsProject.instance().mapLayers().values()]
            for lyr in lyrs:
                print("Layer name: {0}".format(lyr.name()))
                print("Table itme name: {0}".format(item))
                if [item] == [lyr.name()]:
                    iface.layerTreeView().setCurrentLayer(lyr)
            iface.layerTreeView().setSelectionMode(QAbstractItemView.ExtendedSelection)