# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerTreeToImage
                                 A QGIS plugin
 This plugin exports each layer in the table of contents (tree) to an image.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-17
        git sha              : $Format:%H$
        copyright            : (C) 2020 by GETC
        email                : ahmad@getc.co.jp
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QTimer
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QAbstractItemView, QToolBar

from qgis.core import *
from qgis.utils import iface

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Layer_Tree_To_Image_dialog import LayerTreeToImageDialog
import os.path, time
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt
from PyQt5 import QtCore


class LayerTreeToImage:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LayerTreeToImage_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

#        # Create the dialog (after translation) and keep reference
        self.dlg = LayerTreeToImageDialog()


        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Layer Tree To Image')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LayerTreeToImage', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Layer_Tree_To_Image/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Layer tree to image'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Layer Tree To Image'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = LayerTreeToImageDialog()
            # Disable any action behind the tool dialog window
            self.dlg.setModal(True)

        # show the dialog
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if not result:
        # See if Cancel was pressed
            out_path = self.dlg.OutFolderTxtEdit.setText("")
            self.dlg.group.setExclusive(False)
            self.dlg.allLyrRadBtn.setChecked(False)
            self.dlg.allLyrRadBtn_2.setChecked(False)
            self.dlg.selLyrRadBtn.setChecked(False)
            self.dlg.selLyrRadBtn_2.setChecked(False)
            self.dlg.layerTable.setRowCount(0)
            self.dlg.doubleSpinBox.setValue(1)
            self.dlg.doubleSpinBox_2.setValue(1)
            iface.layerTreeView().setSelectionMode(QAbstractItemView.ContiguousSelection)
            iface.layerTreeView().clearSelection()

        if result:
            start_time = time.process_time()
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            out_path = self.dlg.OutFolderTxtEdit.text().strip()
            renderTime = self.dlg.doubleSpinBox.value()
            exportTime = self.dlg.doubleSpinBox_2.value()
            
            layer_names = []
            rows  =  self.dlg.layerTable.rowCount()
            for i in range(rows):
                lyr_name = self.dlg.layerTable.item(i,0)
                layer_names.append(lyr_name.text())               
            lyrs = [lyr.name() for lyr in QgsProject.instance().mapLayers().values() if lyr.name() in layer_names]
            
            prog = QProgressDialog('Exporting to PNG ...', 'Cancel', 0, 0)
            # keep the progress bar on top of the qgis application and disable
            # any actions on the main qgis window
            prog.setWindowModality(QtCore.Qt.ApplicationModal)
            
            self.count = 0            
            def prepareMap():
                iface.actionHideSelectedLayers().trigger()
                # get layer by layer_name
                layer_name = QgsProject.instance().mapLayersByName(lyrs[self.count])[0]
                # select layer
                iface.layerTreeView().setCurrentLayer(layer_name)
                # set selected layer visible
                iface.actionShowSelectedLayers().trigger()

                if prog.wasCanceled():
                    iface.actionHideSelectedLayers().trigger()

                # Wait a second and export the map
                QTimer.singleShot(int(round(renderTime,0)) * 1000, exportMap)

            def exportMap(): 
                self.count
                # save current view as image
                iface.mapCanvas().saveAsImage(os.path.join(out_path, lyrs[self.count] + ".png"))
                # feedback for printed map
                iface.messageBar().pushMessage(
                    '{0}.png exported sucessfully in {1} seconds. Check the <a href="{2}">Destination Folder.</a>'
                    .format(lyrs[self.count],(time.process_time() - start_time),out_path),3, duration=2)

                # get map for every layer in layer_list except basemap
                # such as OSM Standard. Otherwise -2 should -1 to export
                # all layers including basemap
                if prog.wasCanceled():
                    iface.messageBar().pushMessage(
                        'The process was interrupted by a user. Not all files were exported.'
                        .format(out_path),2, duration=0)
                    return None
                
                if self.count < len(lyrs)-1:
                    # Wait a second and prepare next map (timer is needed because otherwise all images have the same content 
                    # the script excecutes faster then the mapCanvas can be reloaded
                    QTimer.singleShot(int(round(exportTime,0)) * 1000, prepareMap) 
                self.count += 1

                if self.count == len(lyrs):
                    prog.close()
                
            prepareMap()
            print(len(lyrs))
            
            self.dlg.OutFolderTxtEdit.setText("")
            self.dlg.group.setExclusive(False)
            self.dlg.allLyrRadBtn.setChecked(False)
            self.dlg.selLyrRadBtn.setChecked(False)
            self.dlg.allLyrRadBtn_2.setChecked(False)
            self.dlg.selLyrRadBtn_2.setChecked(False)  
            self.dlg.layerTable.setRowCount(0)
            self.dlg.doubleSpinBox.setValue(1)
            self.dlg.doubleSpinBox_2.setValue(1)
            iface.layerTreeView().setSelectionMode(QAbstractItemView.ContiguousSelection)

        

        